name: Verify signatures

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:

jobs:
  test_cosign_action:
    runs-on: ubuntu-latest

    permissions:
      actions: none

    name: Install Cosign and test presence in path
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Check signed/unsigned image!
        run: |
          cosign verify --key cosign.pub public.ecr.aws/d1r0p2a6/ecs-cosign-demo2:signed && \
          ! cosign verify --key cosign.pub public.ecr.aws/d1r0p2a6/ecs-cosign-demo2:unsigned
